My memes screen
Ozzorany/ExtreMeme pull request #4
Opened 2020-12-17 23:48 UTC by Ozzorany

2020-12-17 23:49 UTC, Ozzorany commented
@yarivg  Not finished yet- but after that, you can start and use the meme service & try to get the images from the storage of firebase

2020-12-18 12:58 UTC, yarivg requested changes

2020-12-18 12:58 UTC, yarivg commented on app/src/main/java/com/example/extrememe/MyMemesFragment.java
> +                        Log.d("TAG","meme " + position + " was clicked ");
why tag?

2020-12-18 12:58 UTC, yarivg commented on app/src/main/java/com/example/extrememe/services/DatabaseDataLoader.java
> +            storageRef = storage.getReferenceFromUrl(url);
the storage object might be null - android is known for static object get deliminated during lifecycle
https://stackoverflow.com/questions/9541688/static-variable-null-when-returning-to-the-app

- [ ]  FirebaseStorage.getInstance().getReferenceFromUrl(url)

2020-12-18 13:30 UTC, Ozzorany commented on app/src/main/java/com/example/extrememe/MyMemesFragment.java
> +                        Log.d("TAG","meme " + position + " was clicked ");
Just wanted to check if the listener works well.
I've just removed it.

2020-12-19 10:23 UTC, merged